language: node_js
node_js:
    - 14.15.4
install:
    - npm install
script:
    # Prettier
    - npm run format:check
    # ESLint
    - npm run lint:check
    # Build
    - npm run serve:android:anew
