language: node_js
node_js:
    - 14.15.4
install:
    - npm install
script:
    # Create environment variables
    - npm run create:capacitor.config
    - npm run create:config
    # Prettier
    - npm run format:check
    # ESLint
    - npm run lint:check
    # Build
    - npm run serve:android:anew
